<?php

/**
 * @file
 * The islandora_internet_archive_bookreader_custom moudule.
 */

//define('ISLANDORA_SOLR_VIEW_FEED_SELECTOR_COLLECTION', 'collection_selector');


/**
 * Implements hook_menu().
 */
function islandora_internet_archive_bookreader_custom_menu() {
    
    module_load_include('module', 'islandora', 'islandora');
    
    $items['islandora/object/%islandora_object/pdf_generator'] = array(
        'title' => 'Generate Book PDF',
        'page callback' => 'islandora_internet_archive_bookreader_custom_pdf_generator',
        'page arguments' => array(2),
        'type' => MENU_LOCAL_TASK,
        'access callback' => 'islandora_object_manage_access_callback',
        'weight' => 5,
        'access arguments' => array(
        array(
          ISLANDORA_MANAGE_PROPERTIES,
          ISLANDORA_METADATA_EDIT,
          ISLANDORA_ADD_DS,
          ISLANDORA_PURGE,
          ISLANDORA_INGEST,
        ), 2),
    );
    
    $items['islandora/object/%islandora_object/custom/%/%islandora_datastream/download'] = array(
        'page callback' => 'islandora_bookreader_custom_datastream_download',
        'page arguments' => array(4,5),
        'type' => MENU_CALLBACK,
        'access callback' => 'islandora_datastream_access',
        'access arguments' => array(ISLANDORA_VIEW_OBJECTS, 5),
        'load arguments' => array(2),
    );
  return $items;
}

//function islandora_internet_archive_bookreader_custom_menu_alter(array &$items) {
//    
//    module_load_include('module', 'islandora', 'islandora');
//    
//    $items['islandora/object/%islandora_object/pdf_generator'] = array(
//        'title' => 'Generate Book PDF',
//        'page callback' => 'islandora_internet_archive_bookreader_custom_pdf_generator',
//        'page arguments' => array(2),
//        'type' => MENU_LOCAL_TASK,
//        'access callback' => 'islandora_object_manage_access_callback',
//        'weight' => 5,
//        'access arguments' => array(
//        array(
//          ISLANDORA_MANAGE_PROPERTIES,
//          ISLANDORA_METADATA_EDIT,
//          ISLANDORA_ADD_DS,
//          ISLANDORA_PURGE,
//          ISLANDORA_INGEST,
//        ), 2),
//    );
//    
//}

function islandora_internet_archive_bookreader_theme_registry_alter(&$theme_registry) {
    $theme_registry["islandora_internet_archive_bookreader"]["includes"][] = drupal_get_path('module', 'islandora_internet_archive_bookreader_custom') . "/theme/theme.inc";
    $theme_registry["islandora_internet_archive_bookreader"]["preprocess functions"][] = "islandora_internet_archive_bookreader_preprocess_html";
    $theme_registry["islandora_book_page"]["includes"][] = drupal_get_path('module', 'islandora_internet_archive_bookreader_custom') . "/theme/theme.inc";
    $theme_registry["islandora_book_page"]["preprocess functions"][] = "islandora_book_page_preprocess_html";
}

function islandora_internet_archive_bookreader_custom_pdf_generator(AbstractObject $object) {

    module_load_include('inc', 'islandora_internet_archive_bookreader_custom', 'includes/book_pdf_generator');
    $pid = $object->id;
    $message = islandora_internet_archive_bookreader_custom_pdf_generator_pid($pid);
    drupal_set_message(t('%d datastream sucessfully created from book %o', array(
        '%d' => 'PDF',
        '%o' => $object->label))
    );
    $url = $GLOBALS['base_url']."/islandora/object/".$pid;    
    drupal_goto($url);
    exit();
}

function islandora_internet_archive_bookreader_custom_block_info() {
  $blocks = array();

  $blocks['social_link_block'] = array(
    'info' => t('Block displaying social links for islandora bookreader'),
  );
  
  $blocks['reader_block'] = array(
    'info' => t('Block displaying download links for islandora bookreader'),
  );
  
  return $blocks;
}

/**
* Implements hook_block_view().
*/
function islandora_internet_archive_bookreader_custom_block_view($delta = '') {
    
    $block = array();    
    module_load_include('module', 'islandora', 'islandora');
    module_load_include('inc', 'islandora_internet_archive_bookreader_custom', 'includes/utilities');
    module_load_include('inc', 'islandora_embed', 'includes/response_generator');
    
    try{
        if($pid = get_pid_by_url()){

            $object = islandora_object_load($pid);
            $fedoraObjExt = new FedoraObjectExtended($object->id, $object->repository);
            $model = $fedoraObjExt->getFedoraObjectModel();            
            if(empty($model) || $model !== "bookCModel"){
                return;
            }
            switch ($delta) {
                case 'social_link_block':
                    $block['subject'] = 'Share this book:';
                    $block['content'] = bookreader_custom_social_link_block_view($object);
                    break;
                case 'reader_block':
                    $block['subject'] = 'Book and pages download links:';
                    $block['content'] = bookreader_custom_download_block_view($object);
                    break;
            }
        }
    }
    catch(Exception $e){
        drupal_set_message(t('Unable to build the custom islandora book blocks %e', array('%e' => $e)), 'error');
    }
    return $block;
}

function islandora_bookreader_custom_datastream_download($newFileName, AbstractDatastream $datastream) {
    module_load_include('inc', 'islandora', 'includes/mimetype.utils');
    module_load_include('inc', 'islandora', 'includes/datastream');

    $GLOBALS['devel_shutdown'] = FALSE;

    try{
        if ($version !== NULL) {
          if (isset($datastream[$version])) {
            $datastream = $datastream[$version];
          }
          else {
            return drupal_not_found();
          }
        }
        header('Content-type: ' . $datastream->mimetype);
        if ($datastream->controlGroup == 'M' || $datastream->controlGroup == 'X') {
          header('Content-length: ' . $datastream->size);
        }

        $extension = '.' . islandora_get_extension_for_mimetype($datastream->mimetype);
        // Prevent adding on a duplicate extension.
        $label = $datastream->label;
        $extension_length = strlen($extension);
        $duplicate_extension_position = strlen($label) > $extension_length ?
          strripos($label, $extension, -$extension_length) :
          FALSE;
        $filename = $newFileName;
        if ($duplicate_extension_position === FALSE) {
          $filename .= $extension;
        }
        header("Content-Disposition: attachment; filename=\"$filename\"");


        $cache_check = islandora_view_datastream_cache_check($datastream);
        if ($cache_check !== 200) {
          if ($cache_check === 304) {
            header('HTTP/1.1 304 Not Modified');
          }
          elseif ($cache_check === 412) {
            header('HTTP/1.0 412 Precondition Failed');
          }
        }
        islandora_view_datastream_set_cache_headers($datastream);

        drupal_page_is_cacheable(FALSE);

        // New content needed.
        if ($cache_check === 200) {
          // We need to see if the chunking is being requested. This will mainly
          // happen with iOS video requests as they do not support any other way
          // to receive content for playback.
          $chunk_headers = FALSE;
          if (isset($_SERVER['HTTP_RANGE'])) {
            // Set headers specific to chunking.
            $chunk_headers = islandora_view_datastream_set_chunk_headers($datastream);
          }
          // Try not to load the file into PHP memory!
          // Close and flush ALL the output buffers!
          while (@ob_end_flush()) {
          };

          if (isset($_SERVER['HTTP_RANGE'])) {
            if ($chunk_headers) {
              islandora_view_datastream_deliver_chunks($datastream, $chunk_headers);
            }
          }
          else {
            $datastream->getContent('php://output');
          }
        } 
    }
    catch (Exception $ex){
        drupal_set_message(t('Cannot download the datastream for this link %e', array('%e' => $ex)), 'error');
    }

    exit();
}

